### ISSUE TITLE
BUG Rendering entity in world

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#417] opened 2024-08-01 11:13 UTC
```
---- Minecraft Crash Report ----
// My bad.

Time: 2024-08-01 15:41:31
Description: Rendering entity in world

java.lang.ClassCastException: class net.minecraft.class_549 cannot be cast to class net.minecraft.class_572 (net.minecraft.class_549 and net.minecraft.class_572 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @f2f2cc1)
	at com.minelittlepony.unicopia.client.render.AmuletFeatureRenderer.render(AmuletFeatureRenderer.java:52)
	at com.minelittlepony.unicopia.client.render.AccessoryFeatureRenderer.lambda$render$1(AccessoryFeatureRenderer.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.minelittlepony.unicopia.client.render.AccessoryFeatureRenderer.render(AccessoryFeatureRenderer.java:50)
	at com.minelittlepony.unicopia.client.render.AccessoryFeatureRenderer.method_4199(AccessoryFeatureRenderer.java:23)
	at net.minecraft.class_922.method_4054(class_922.java:144)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minelittlepony.unicopia.client.render.AmuletFeatureRenderer.render(AmuletFeatureRenderer.java:52)
	at com.minelittlepony.unicopia.client.render.AccessoryFeatureRenderer.lambda$render$1(AccessoryFeatureRenderer.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.minelittlepony.unicopia.client.render.AccessoryFeatureRenderer.render(AccessoryFeatureRenderer.java:50)
	at com.minelittlepony.unicopia.client.render.AccessoryFeatureRenderer.method_4199(AccessoryFeatureRenderer.java:23)
	at net.minecraft.class_922.method_4054(class_922.java:144)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)

-- Entity being rendered --
Details:
	Entity Type: minecraft:horse (net.minecraft.class_1498)
	Entity ID: 6127
	Entity Name: 马
	Entity's Exact location: 807.91, 96.00, 14344.97
	Entity's Block location: World: (807,96,14344), Section: (at 7,0,8 in 50,6,896; chunk contains blocks 800,-64,14336 to 815,319,14351), Region: (1,28; contains chunks 32,896 to 63,927, blocks 512,-64,14336 to 1023,319,14847)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [class_746['NoodAifie'/6126, l='ClientLevel', x=807.91, y=96.84, z=14344.97]]
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_910@1e9f2449
	Location: 0.00,-3.61,0.00 - World: (0,-4,0), Section: (at 0,12,0 in 0,-1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 173.81427
	Delta: 0.36001492
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Uptime --
Details:
	JVM uptime: 92.188s
	Wall uptime: 78.859s
	High-res time: 46.599s
	Client ticks: 583 ticks / 29.150s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Affected level --
Details:
	All players: 1 total; [class_746['NoodAifie'/6126, l='ClientLevel', x=807.91, y=96.84, z=14344.97]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,119,0), Section: (at 0,7,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 40865213 game time, 5171037 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 173
	pehkui:debug/render/entity: minecraft:horse

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Minecraft-Mod-Language-Modpack-Converted-1.20.4.zip, fabric, allmusic_client, appleskin, artifacts, balm-fabric, beautify, betterf3, bigpony, cardinal-components, cardinal-components-base, cardinal-components-block, cardinal-components-chunk, cardinal-components-entity, cardinal-components-item, cardinal-components-level, cardinal-components-scoreboard, cardinal-components-world, chatimage, cloth-config, config_toolkit, controlling, crafttweaker, endrem, extended_drawers, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabwork, fancymenu, ftbchunks, ftbessentials, ftblibrary, ftbteams, graphlib, hdskins, indium, inventoryprofilesnext, iris, jade, jei, kanos_config, kmodlib-overlay, konkrete, lambdynlights, libipn, libnetworkstack, minelp, modmenu, mson, nochatreports, noindium, patchouli, pehkui, pride, reach-entity-attributes, searchables, sodium, spectrelib, spruceui, step-height-entity-attribute, terraform-wood-api-v1, travelersbackpack, travelerstitles, trinkets, unicopia, veinmining, voicechat, waystones, worldedit, xaerominimap, xaeroplus, xaeroworldmap, yet_another_config_lib_v3

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1407130504 bytes (1341 MiB) / 2894069760 bytes (2760 MiB) up to 6014631936 bytes (5736 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Virtual Display Device
	Graphics card #0 vendor: Huawei
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.0.9
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a6
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1934
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 4.27
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 4.27
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 4.27
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 4.27
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 4.27
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 4.27
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 25324.24
	Virtual memory used (MB): 12083.84
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 34.50
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn860m -Xmx5734m
	Fabric Mods: 
		allmusic_client: AllMusic Client 3.0.0
		appleskin: AppleSkin 2.5.1+mc1.20.3
		architectury: Architectury 11.1.17
		artifacts: Artifacts 10.0.11
			expandability: ExpandAbility 10.0.1
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		balm-fabric: Balm 9.0.8
		beautify: Beautify 1.2.0+1.20.4
		betterf3: BetterF3 9.0.2
		bigpony: Big Pony 1.11.2+1.20.4
		cardinal-components: Cardinal Components API 5.4.0
			cardinal-components-block: Cardinal Components API (blocks) 5.4.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.4.0
			cardinal-components-item: Cardinal Components API (items) 5.4.0
			cardinal-components-level: Cardinal Components API (world saves) 5.4.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.4.0
			cardinal-components-world: Cardinal Components API (worlds) 5.4.0
		chatimage: ChatImage 1.2.4+1.20.4+fabric
			actionlib: ActionLib 1.0.2-fabric
			io_github_kituin_chatimagecode: ChatImageCode 0.9.7
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 15.0.0.2
		collective: Collective 7.64
		controlling: Controlling 15.0.5
		crafttweaker: CraftTweaker 17.0.19
			org_reflections_reflections: reflections 0.10.2
		diamondchestshop: Diamond Chest Shop 1.2.6+1.20
		diamondeconomy: Diamond Economy 1.5.6
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
			placeholder-api: Placeholder API 2.2.0+1.20.2
		endrem: End Remastered 5.2.4
		extended_drawers: Extended Drawers 2.1.1+mc.1.20.4
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
			graphlib: Graph Lib 1.4.0+1.20.4
				kmodlib-overlay: KModLib Overlay 0.2.13+1.20.3
				libnetworkstack: Lib Network Stack 0.11.0-pre.1
			noindium: No Indium? 1.1.0+1.20.4
			yet_another_config_lib_v3: YetAnotherConfigLib 3.3.1+1.20.4
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fancymenu: FancyMenu 3.2.3
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		firstjoinmessage: First Join Message 3.5
		framework: Framework 0.7.6
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
		ftbchunks: FTB Chunks 2004.1.2
		ftbessentials: FTB Essentials 2004.1.2
		ftblibrary: FTB Library 2004.2.2
		ftbranks: FTB Ranks 2004.2.0
		ftbteams: FTB Teams 2004.1.2
		hdskins: HD Skins 6.12.2+1.20.4
		i18nupdatemod: I18nUpdateMod 3.5.5
		indium: Indium 1.0.30+mc1.20.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		iris: Iris 1.7.0+mc1.20.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 13.3.1
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 17.3.0.52
		kirin: Kirin UI 1.17.1+1.20.4
		konkrete: Konkrete 1.9.2
		lambdynlights: LambDynamicLights 2.3.4+1.20.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.3+1.20.2
		libipn: libIPN 4.0.2
		melody: Melody 1.0.3
		minecraft: Minecraft 1.20.4
		minelp: Mine Little Pony 4.11.7+1.20.4
			mson: Mson 1.9.3+1.20.2
		modmenu: Mod Menu 9.2.0-beta.2
		mousetweaks: Mouse Tweaks 2.26
		nochatreports: No Chat Reports 1.20.4-v2.6.0
		patchouli: Patchouli 1.20.4-85-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		searchables: Searchables 1.0.6
		sodium: Sodium 0.5.8+mc1.20.4
		travelersbackpack: Traveler's Backpack fabric-1.20.4-9.4.6
			reach-entity-attributes: Reach Entity Attributes 2.5.0
		travelerstitles: Traveler's Titles 1.20.4-Fabric-4.4.1
		trinkets: Trinkets 3.8.1
			cardinal-components-base: Cardinal Components API (base) 5.4.0
			cardinal-components-entity: Cardinal Components API (entities) 5.4.0
		unicopia: Unicopia 1.3.8+1.20.4
			fabwork: Fabwork 1.3.0+1.20.2
			romanizer: Romanizer 1.0.2
			terraform-wood-api-v1: Terraform Wood API (v1) 8.0.0-beta.1
		veinmining: Vein Mining 3.1.1+1.20.4
			spectrelib: SpectreLib 0.15.2+1.20.4
		voicechat: Simple Voice Chat 1.20.4-2.5.15
		waystones: Waystones 16.0.5
		worldedit: WorldEdit 7.3.0+6678-55745ad
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroplus: XaeroPlus 2.9
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.2
		xaeroworldmap: Xaero's World Map 1.38.4
		yungsapi: YUNG's API 1.20.4-Fabric-4.4.3
	Loaded Shaderpack: (off)
	Launched Version: PonyGalaxy1.34
	Launcher name: PCL
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 30.0.101.1934, Intel
	Window size: 2520x1539
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/12 chunks
	Resource Packs: file/Minecraft-Mod-Language-Modpack-Converted-1.20.4.zip, fabric
	Current Language: zh_cn
	Locale: zh_CN
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12500H
```

**Comment by Sollace** [comment] 2024-08-01 14:18
Duplicate of #401

**Closed as completed by Sollace** 2024-08-01 14:18 UTC
Labels: bug

**Comment by OakPlatinum** [comment] 2024-08-01 22:32
@Sollace Er, it's a little different from #401.
A changeling player's disguising triggers #401.
Using a horse armor on a horse triggers this one.

**Comment by Sollace** [comment] 2024-08-02 05:24
> @Sollace Er, it's a little different from #401. A changeling player's disguising triggers #401. Using a horse armor on a horse triggers this one.

I'm looking at the stacktrace. It's the same error.
