### ISSUE TITLE
items disappear when dropped/mined

### ISSUE THREAD

**Issue by nya-wn** [Sollace/Unicopia#126] opened 2023-06-27 06:14 UTC
I am playing All The Fabric 4 through ATLauncher, and for some reason adding Unicopia makes it to where any items I drop disappear when I join my friend's server. They're still there, they just don't render in. If I walk over there, I pick them up. 

This only occurs when I join my friend's server. If I launch in single player, or host the server myself, I have no problems.

**Comment by Sollace** [comment] 2023-06-27 19:51
Can you add your client logs please?

**Comment by Sollace** [comment] 2023-06-27 19:51
I'm going to tag it as compatibility for the time being, since it sounds like other mods are involved.

**Comment by nya-wn** [comment] 2023-06-27 22:24
[2023-06-27-7.log.gz](https://github.com/Sollace/Unicopia/files/11887788/2023-06-27-7.log.gz)

hopefully this is the right item! ;v; sorry if it's not orz

**Comment by Sollace** [comment] 2023-06-28 16:47
Sorry, there's nothing in that log I can see that would indicate the issue. Do you have the log from when you were in multiplayer and experiencing this issue?

**Comment by nya-wn** [comment] 2023-06-28 23:02
that's weird ;;; I'm pretty sure that's the multi player log. is there anywhere else i can look??

**Comment by nya-wn** [comment] 2023-06-29 03:05
https://paste.atlauncher.com/view/79537106-6be7-4635-90f4-aca439aaaafb

here's the information from the console, and i deleted all the previous logs to make sure i'm sending the proper one. ill send the two in the folder, just in case
[2023-06-28-2.log.gz](https://github.com/Sollace/Unicopia/files/11901613/2023-06-28-2.log.gz)
[2023-06-28-1.log.gz](https://github.com/Sollace/Unicopia/files/11901614/2023-06-28-1.log.gz)

**Comment by nya-wn** [comment] 2023-06-29 03:05
https://paste.atlauncher.com/view/79537106-6be7-4635-90f4-aca439aaaafb

here's the information from the console, and i deleted all the previous logs to make sure i'm sending the proper one. ill send the two in the folder, just in case
[2023-06-28-1.log.gz](https://github.com/Sollace/Unicopia/files/11901618/2023-06-28-1.log.gz)
[2023-06-28-2.log.gz](https://github.com/Sollace/Unicopia/files/11901619/2023-06-28-2.log.gz)

(i closed by accident sorry qq)

**Comment by nya-wn** [comment] 2023-08-01 02:54
hello! just checking in

**Comment by Sollace** [comment] 2023-08-01 08:33
None of these logs contain useful information. I do see you're using AT launcher, so can you try to reproduce it in the vanilla launcher and post your latest.log, not the launcher output, please?

**Comment by Sollace** [comment] 2023-09-16 17:28
This issue hasn't had any update in over a month. Closing as it's probably not relevant to the current version anyway.

**Closed as not planned** 2023-09-16 17:29 UTC
Labels: bug, compatibility
