### ISSUE TITLE
kirin level randomly reset

### ISSUE THREAD

**Issue by ghost** [Sollace/Unicopia#452] opened 2024-09-06 02:17 UTC
noticed level had dropped to 2 (checked spellbook). tried leaving the game and rejoining, but then it dropped to 1. know of another (pegasus) who had a similar issue, their flight capacity being halved for no apparent reason.

**Comment by Sollace** [comment] 2024-09-21 19:54
I haven't seen this at all in my testing. What version are you using?

**Comment by OakPlatinum** [comment] 2024-09-22 09:52
I've seen this. It dropped to 1, and then restored after my rejoining. Never see it twice.

**Comment by Sollace** [comment] 2024-09-22 16:26
Hm okay. So maybe just an upgrading thing? If it only happens once it's probably not an issue

**Comment by EternaDash** [comment] 2024-09-23 01:06
New Tag Just Dropped

**Comment by fin600** [comment] 2024-09-23 03:25
It happens to any race that uses levels, most frequently with unicorn amulet use. The data for the level isn't lost, it just becomes 1 until something calls on or resaves the level again. The easiest way to trigger it is be a batpony with a unicorn amulet and start doing things that trigger values to be saved like being in sunlight or casting spells.

**Comment by EternaDash** [comment] 2024-09-23 14:45
> The easiest way to trigger it is be a batpony with a unicorn amulet and start doing things that trigger values to be saved like being in sunlight or casting spells.

Ain't Working For Me Trying To Test It

**Comment by RomaTomatoPlant** [comment] 2024-09-23 23:00
We are playing on 1.20.1 latest version of unicopia 

On a server I play on it happens rather often due to the player count, it only happens to different ponies usually (sometimes the same pony 2 or 3 times) 

It USUALLY tends to fix itself but theres been a few instances or so where the level did not go back even after dying, logging on and off, waiting long periods to fix itself 

It tends to happen the most when players have been playing for more than 3-4 hours at a time, or when trying to make a spell too large i.e an extremely powerful blackhole spell or just more negative spells in general, ive also noticed it happens to players that are around the levels of 20-30 and for some reason it primarily happens to Bats, Unicorns and Ponies wearing the Unicorn Amulet 

The biggest issue is that you cannot do the command to reset the level for other people and the admins have to come on and then give the person perms so the person themselves are able to set the level to what it was (especially in cases where the level doesn't naturally go back after a bit of time) Ideally maybe just let the setting level command be able to be have other players names typed into it so when this issue does happen admins dont need to give perms and can just set the players level themselves?

**Comment by Sollace** [comment] 2024-10-29 16:56
This MAY have been fixed in 1.21 with the upcoming release. Turns out there was some issues with the data tracking and how it was sending the packets/reusing buffers that also caused a lot of other reported issues with multiplayer.

**Comment by MactoPerFuror** [comment] 2024-10-29 23:36
Any chance a patch for 1.20.1 could happen? Totally get if it’s too messy to backport, just figured I’d ask. Thanks for all the work on this!

**Comment by Sollace** [comment] 2024-10-30 22:25
> Any chance a patch for 1.20.1 could happen? Totally get if it’s too messy to backport, just figured I’d ask. Thanks for all the work on this!

I _may_ do a backport if the bug is confirmed to be fixed. It's not straightforward to do though as the way networking works changed a lot in 1.21

**Comment by Sollace** [comment] 2024-12-10 22:12
Closing as stale

**Closed as not planned by Sollace** 2024-12-10 22:12 UTC
Labels: unconfirmed
