### ISSUE TITLE
remove curses from entchantment table

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#306] opened 2024-03-18 20:47 UTC
curses in minecraft are not supposed to be added by the enchantment table

they are inteded to be on items you find and can be added using books you can get from villages

**Comment by Sollace** [comment] 2024-03-18 22:09
This is the intended behaviour. The enchantments added by unicopia are marked as curses because for lore reasons, that's what they are,  but they're still designed to be useful to the player in some way.

**Comment by MimzyFang** [comment] 2024-03-20 20:03
> This is the intended behaviour. The enchantments added by unicopia are marked as curses because for lore reasons, that's what they are, but they're still designed to be useful to the player in some way.

could you at least make it that these curses are removable because I hate something just to throw it away because it got stressed

**Closed as completed** 2024-03-20 22:16 UTC
Labels: bug, fixed
