### ISSUE TITLE
Water Takes You Up While Flying Rather Than Down

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#369] opened 2024-05-26 10:43 UTC
![image_2024-05-26_034129202](https://github.com/Sollace/Unicopia/assets/153742870/d946d30e-5210-4501-acf2-ad7ebc16a8b1)
Didn't Even Know That Was Unintentional, To Be Honest It's Kinda Annoying To Be Constantly Launched Up Into The Stratosphere For Going Over A Single Smidge Of Water So I Will Rejoice When Fixed.

**Comment by PrinceDrowsy** [comment] 2024-05-26 15:26
> ![image_2024-05-26_034129202](https://private-user-images.githubusercontent.com/153742870/333872433-d946d30e-5210-4501-acf2-ad7ebc16a8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzczMzUsIm5iZiI6MTcxNjczNzAzNSwicGF0aCI6Ii8xNTM3NDI4NzAvMzMzODcyNDMzLWQ5NDZkMzBlLTUyMTAtNDUwMS1hY2YyLWFkN2ViYzE2YThiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNTIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjRiMTcyOGQ0OWQ1NDgwNWFkOTk1M2U5YTYzNWNjM2ZjYTk1ZmIyY2E1Mjk0NjgxYTIxNDc2NDY3Y2I4NjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xmxGBLY-zzYej1JEK06Dw81qjdiDJa1cSzUPOpOLe8c) Didn't Even Know That Was Unintentional, To Be Honest It's Kinda Annoying To Be Constantly Launched Up Into The Stratosphere For Going Over A Single Smidge Of Water So I Will Rejoice When Fixed.

It originally brought you down, hence the text, however this feature was initially made in a beta build, and partially altered in accordance to a suggestion I made regarding how birds in real life use the wind currents over the ocean to cross large distances! #176 I quite like this feature, so I wouldn't want to see it go. Especially since I do believe it's an improvement over sinking because of water, as someone who's played both builds. However, if it is possible, it could be nice to make it so there has to be a larger number of "water blocks" in the area to cause the affect rather than any puddle having the wind current strength of an entire ocean, haha.

**Comment by EternaDash** [comment] 2024-05-26 17:08
> It originally brought you down, hence the text, however this feature was initially made in a beta build, and partially altered in accordance to a suggestion I made regarding how birds in real life use the wind currents over the ocean to cross large distances!

Ah, I See. Strange It Wasn't Updated To Reflect The Change.

> if it is possible, it could be nice to make it so there has to be a larger number of "water blocks" in the area to cause the affect rather than any puddle having the wind current strength of an entire ocean, haha.

Yeah That'd Certainly Fix The Issue Of Every Block Of Water Being It's Own Space Program, And Wouldn't Remove The Feature Itself For When Going Over Oceans. I Suppose Another Way Would To Just Only Affect Water In Ocean Biomes, But That Could Result In Some Jank If The Ocean Is Covered Up Except For One Tile, And With Artificial Oceans That Realistically Should Have The Same Effect But Are Built Outside Ocean Biomes, So I Like Your Idea More.

**Comment by Sollace** [comment] 2024-05-26 18:02
Closing this as it's not a bug. I'll note of the suggestion to take int account the depth though.

**Closed as not planned by Sollace** 2024-05-26 18:02 UTC
