### ISSUE TITLE
Pegasus fall damage bug

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#382] opened 2024-06-11 13:47 UTC
Recently I playing as a pegasus in a sever，somehow I sometime receive fall damage even I land gently，sometime it even kill me，probably a bug

**Comment by Sollace** [comment] 2024-06-11 14:08
Known bug. Wait for the update.

**Comment by Sollace** [comment] 2024-06-11 14:08
Duplicate of #344

**Closed as completed** 2024-06-23 14:30 UTC
Labels: bug, fixed
