### ISSUE TITLE
[bug] Disguising as Twittermites on servers soft-bans players.

### ISSUE THREAD

**Issue by PoneyClairDeLune** [Sollace/Unicopia#46] opened 2022-01-15 18:07 UTC
If changelings disguise themselves as Twittermites on servers, they will be kicked immediately and upon every join, effectively soft-banning themselves.

**Version**: Beta 15 for 1.18.X

## Error logs
```
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:543) ~[server-intermediary.jar:?]                                                                        at net.minecraft.class_3244.method_18784(class_3244.java:213) ~[server-intermediary.jar:?]                                                                        at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[server-intermediary.jar:?]                                                                        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[server-intermediary.jar:?]                                                        at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]                                                                         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]                                                        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]                                                       at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]                           Caused by: java.lang.AbstractMethodError: Receiver class com.minelittlepony.unicopia.entity.FairyEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1937 getWorld()' of interface com.minelittlepony.unicopia.WeaklyOwned.
        at com.minelittlepony.unicopia.WeaklyOwned.getMaster(WeaklyOwned.java:42) ~[Unicopia-1.0.0-beta.15.jar:?]                                                         at com.minelittlepony.unicopia.entity.behaviour.EntityAppearance.getFlightType(EntityAppearance.java:221) ~[Unicopia-1.0.0-beta.15.jar:?]                         at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.minelittlepony.unicopia.entity.behaviour.Disguise.getFlightType(Disguise.java:34) ~[Unicopia-1.0.0-beta.15.jar:?]                                          at com.minelittlepony.unicopia.entity.player.PlayerPhysics.lambda$getFlightType$1(PlayerPhysics.java:144) ~[Unicopia-1.0.0-beta.15.jar:?]                         at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.minelittlepony.unicopia.entity.player.PlayerPhysics.getFlightType(PlayerPhysics.java:144) ~[Unicopia-1.0.0-beta.15.jar:?]                                  at com.minelittlepony.unicopia.entity.player.PlayerPhysics.tick(PlayerPhysics.java:190) ~[Unicopia-1.0.0-beta.15.jar:?]                                           at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.minelittlepony.unicopia.entity.player.Pony.tick(Pony.java:374) ~[Unicopia-1.0.0-beta.15.jar:?]                                                             at net.minecraft.class_1309.handler$zpf001$afterTick(class_1309.java:7678) ~[server-intermediary.jar:?]                                                           at net.minecraft.class_1309.method_5773(class_1309.java:2428) ~[server-intermediary.jar:?]                                                                        at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[server-intermediary.jar:?]                                                                         at net.minecraft.class_3222.method_14226(class_3222.java:479) ~[server-intermediary.jar:?]                                                                        ... 9 more
```

I hate Termux's copying bugs.

**Comment by Sollace** [comment] 2022-01-15 22:56
Duplicate of #44

**Closed as completed by Sollace** 2022-01-15 22:56 UTC
